---
namespace: smougenot
name: proxmox_openssh
version: 1.0.0
readme: README.md
authors:
  - Sylvain Mougenot <sylvain@mougenot.link>

description: Proxmox Cluster management via openssh

license:
  - GPL-2.0-or-later

tags:
  - 'cluster'
  - 'hypervisor'
  - 'infrastructure'
  - 'proxmox'
  - 'pve'
  - 'virtualization'

dependencies: {}
repository: https://github.com/smougenot/proxmox_openssh
documentation: https://github.com/smougenot/proxmox_openssh
homepage: https://github.com/smougenot/proxmox_openssh
issues: https://github.com/smougenot/proxmox_openssh/issues
build_ignore: []
