---
extends: default

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  colons:
    max-spaces-after: -1
    max-spaces-before: 0
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 111
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

ignore: |
  .cache
  .venv
  .vscode
